name: sadaqah_manager
description: Zakath &amp; Sadaqah Manager for muslims worldwide

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.3.0+34

environment:
  sdk: ">=2.1.0 <3.0.0"
  scoped_model: ^1.0.1

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+3
  path_provider: any
  share: ^2.0.1
  font_awesome_flutter: ^9.0.0
  date_format: ^2.0.2
  datetime_picker_formfield: ^2.0.0
  firebase_auth: ^1.1.2
  firebase_remote_config: ^0.9.0-dev.0
  google_sign_in: ^5.0.2
  charts_flutter: ^0.10.0
  package_info: ^2.0.0
  url_launcher: ^6.0.3
  geolocator: ^7.0.3
  geocoding: ^2.0.0
  easy_localization: ^3.0.0
  http: ^0.13.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
#  country_pickers:
  scoped_model: ^1.0.1
  shared_preferences: ^2.0.5

  country_code_picker:
  flutter_country_picker:
  country_pickers:

dev_dependencies:
  test: ^1.17.3
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
#    - lib/resources/assets/
#    - lib/resources/assets/
    - lib/resources/assets/in.png
    - lib/resources/gold.png
    - lib/resources/gold2.png
    - lib/resources/silver.png
    - lib/resources/silver2.png
    - lib/resources/currency.png
    - lib/resources/calculator.png
    - lib/resources/date.png
    - assets/translations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
